services:

  sprint_3_postgres:
    image: postgres:14.11
    ports:
      - "0:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - postgres_to_es/.env
    container_name: sprint_3_postgres
    networks:
      - my_practicum_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

  sprint_3_redis:
    image: redis/redis-stack:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/redis_data
    env_file:
      - postgres_to_es/.env
    container_name: sprint_3_redis
    networks:
      - my_practicum_network
    healthcheck:
      test: redis-cli ping

  sprint_3_elastic_search:
    image: elasticsearch:8.6.2
    ports:
      - "9200:9200"
    volumes:
      - elastic_search_data:/elastic_search_data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    container_name: sprint_3_elastic_search
    networks:
      - my_practicum_network
    healthcheck:
      test: curl -s http://sprint_3_elastic_search:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  sprint_3_app:
    build: .
    ports:
      - "0:8000"
    env_file:
      - postgres_to_es/.env
    depends_on:
      - sprint_3_postgres
      - sprint_3_redis
      - sprint_3_elastic_search
    networks:
      - my_practicum_network
    container_name: sprint_3_app

volumes:
  postgres_data:
  redis_data:
  elastic_search_data:

networks:
  my_practicum_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.58.0/24